name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tsc:
    name: TypeScript Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Register Problem Matcher
        run: echo "::add-matcher::.github/tsc.json"

      - name: Test TypeScript
        run: npm run test:typescript
